### ISSUE TITLE
Configure Security Settings

### ISSUE THREAD

**Issue by minisundev** [GooHwang/WoRoutine-be#1]
## Tasks

- [x]  JwtUtil : Implement JWT utility for authentication and token management
- [x] JwtAuthorizationFilter : Implement JWT authorization filter for token validation and user authentication
- [x] UserDetailsImpl : Implement UserDetails for user authentication
- [x] UserDetailsServiceImpl : Implement UserDetailsServiceImpl for retrieving user details
- [x] WebSecurityConfig : Configure Web Security to utilize JWT for authentication
- [x] Create User Entity
- [x] Create User Repository
