### ISSUE TITLE
Set Global Environments

### ISSUE THREAD

**Issue by minisundev** [GooHwang/WoRoutine-be#6]
## Tasks

- [x] Configure profiles and JPA settings in application.yml
- [x] Implement BaseTime entity for automatic timestamp management
- [x] Configure JPA auditing
- [x] Delete application.properties
